### ISSUE TITLE
[1.10.2] Client Crash using powered Darksteel pick in E+ table

### ISSUE THREAD

**Issue by Morpheus1101** [Darkhax-Minecraft/Enchanting-Plus#49] opened 2016-10-15 02:17 UTC
<Shadows_of_Fire> i just had my pick deleted by the e+ table
<Shadows_of_Fire> if you try to repair an powered dark steel pick it deletes it

Users log file @ https://paste.ee/p/syf4O

Server Console snippet @ http://pastebin.com/XmDnubP7

**Comment by darkhax** [comment] 2016-11-18 00:31
Your pastes are no longer available, assuming this is a duplicate of your other issue though.

**Closed by darkhax** 2016-11-18 00:31 UTC
Labels: duplicate
